spring:
  jpa:
    show-sql: true
    database-platform: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
  datasource:
    url: jdbc:mysql://mysql-server:3306/transaction?createDatabaseIfNotExist=true
    username: root
    password: secretapacas
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    initialization-mode: always